### ISSUE TITLE
missing icons / installation issues?

### ISSUE THREAD

**Issue by nrw303** [tzezar/datagrid#13]
hi,
I'm trying to setup your [basic example](https://tzezars-datagrid.vercel.app/examples/basic) locally.

I am getting a bunch of errors about icons, like 
```
Icon `material-symbols-light/folder-open-outline` not found
```

is there a dependency I'm missing? I must admit I have had to do a lot of "npm --force install" to get this far ;) but I'm keen to try out your datagrid.

thanks

**Comment by tzezar** [comment]
@nrw303 

Fixed. I forgot that I changed the lucide icons used in shadcn-svelte to unplugin-icons. I used svg this time to avoid adding unnecessary deps. 

Could you say more at which stage you were forced to use the `--force`? 
In my case the installation goes smoothly on a new project.

```
PS W:\my-app> npx tzezars-datagrid@latest init
Need to install the following packages:
tzezars-datagrid@1.0.27
Ok to proceed? (y)

√ Where do you want to install the component? ... ./src/lib/datagrid
√ Where is your global CSS file? ... ./src/app.css
√ Where is your tailwind.config.[cjs|js|ts] located? ... ./tailwind.config.ts
√ Do you want to install dependencies? ... yes
Tzezar's Datagrid component installed successfully!
app.css updated successfully!
tailwind.config.ts updated successfully!
Installing dependencies...
papaparse installed successfully.
fast-xml-parser installed successfully.
xlsx installed successfully.
fast-sort installed successfully.
All dependencies installed successfully!
```

**Comment by nrw303** [comment]
I can't remember to be honest, let me try with a new project and report back.

**Comment by nrw303** [comment]
ok, just done a fresh install, new project -> add shadcn and all the necessary components. then I created all the files necessary for the advanced example... upon first run it crashes because the dependencies mentioned in the manual install are not installed, i.e. these npm: fast-sort, papaparse, xlsx, fast-xml-parser

**Comment by tzezar** [comment]
Good to hear that! I'm in the process of writing documentation, if you get stuck somewhere or find an error let me know.

There were a couple of people posting on discord that sometimes they can't deps install. At this moment I don't know why this happens, I have to look into CLI.
