### ISSUE TITLE
CLI error

### ISSUE THREAD

**Issue by bfovez** [tzezar/datagrid#7]
On my first use of the CLI, I came across this error on an all fresh newly installed app (svelte + shadcn): 

```
C:\<dev-folder>\testing-tzezar-grid>npx tzezars-datagrid init
√ Where do you want to install the component? ... ./src/lib/components/datagrid
√ Where is your global CSS file? ... ./src/app.css
√ Where is your tailwind.config.[cjs|js|ts] located? ... ./tailwind.config.ts
√ Do you want to install dependencies? ... yes
Error: [Error: ENOENT: no such file or directory, lstat 'C:\Users\bertrand.fovez\sites\docs\src\lib\datagrid'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '<user-folder>\\sites\\docs\\src\\lib\\datagrid'
}
```
`<dev-folder>` is the folder in which the app resides
`<user-folder>` is my windows user (%USERPROFILE%)

TO REPRODUCE: 

`npm create svelte@latest testing-tzezar-grid && cd testing-tzezar-grid && npx svelte-add@latest tailwindcss && npx shadcn-svelte@latest init && npx tzezars-datagrid init`

Accept all defaults (except for Svelte 5 preview opt-in).

**Comment by tzezar** [comment]
I made a silly mistake in the path definition. It should work now. Use `npx tzezars-datagrid@latest init`.

**Comment by bfovez** [comment]
👍

Le mer. 9 oct. 2024 à 21:04, Sebastian Drozd ***@***.***> a
écrit :
